#ifndef HOGP_CONTROL_EVENTS_H
#define HOGP_CONTROL_EVENTS_H
#include "hogp_common.h"

/**
 * @brief  Enumeration of control event types.
 * These events drive the internal state machine (FSM) of the HOGP application.
 * They are typically generated by BLE stack callbacks or internal logic.
 */
typedef enum {
    HOGP_CEVT_SHUTDOWN,      /**< Request to shut down the application and free resources. */
    HOGP_CEVT_SUSPEND,       /**< Host requested the device to enter/exit Suspend mode. */
    HOGP_CEVT_SET_PROTOCOL,  /**< Host requested a switch between Boot and Report protocols. */
    HOGP_CEVT_CONNECT,       /**< A peer device has successfully connected. */
    HOGP_CEVT_DISCONNECT,    /**< The peer device has disconnected. */
    HOGP_CEVT_ADV_COMPLETE,  /**< Advertising duration finished (timeout or stopped). */
    HOGP_CEVT_ADV_STARTED,   /**< Advertising has successfully started. */
    HOGP_CEVT_NOTIFY_TX,     /**< Notification transmission completed (TX buffer available). */
    HOGP_CEVT_SUBSCRIBE,     /**< Host updated subscription status (CCCD write). */
    HOGP_CEVT_MTU,           /**< MTU size updated for the connection. */
    HOGP_CEVT_BLE_READY,     /**< BLE stack is initialized and ready to start. */
} hogp_control_event_type_t;

/**
 * @brief  Structure representing a control event.
 * Contains the event type and a union of parameters specific to that event.
 */
typedef struct {
    hogp_control_event_type_t type; /**< The type of the control event. */

    union {
        uint8_t suspended;        /**< For HOGP_CEVT_SUSPEND: 1 = Suspend, 0 = Exit Suspend. */
        hogp_protocol_t protocol; /**< For HOGP_CEVT_SET_PROTOCOL: The new protocol mode. */
        uint8_t reason;           /**< For HOGP_CEVT_DISCONNECT: The disconnection reason code. */
        uint8_t mtu;              /**< For HOGP_CEVT_MTU: The new MTU size. */
        uint16_t conn_handle;     /**< For HOGP_CEVT_CONNECT: The handle of the new connection. */
        
        /**
         * @brief Structure for subscription events (HOGP_CEVT_SUBSCRIBE).
         */
        struct {
            uint16_t sub_handle; /**< The attribute handle being subscribed to. */
            uint8_t sub;         /**< Subscription flags: Bit 0 = Indicate, Bit 1 = Notify. */
        };
    };
} hogp_control_event_t;

#endif /* HOGP_CONTROL_EVENTS_H */
