#ifndef HOGP_ERROR_CODES_H
#define HOGP_ERROR_CODES_H

typedef enum {
    HOGP_OK,
    HOGP_NOT_SUBSCRIBED,
    HOGP_TX_NOT_RECEIVED,
    HOGP_NOTHING_TO_SEND,
    HOGP_NOT_SUPPORTED_YET,
    HOGP_NOT_SUPPORTED,
    HOGP_NO_CONTROLS,
    HOGP_POP_FAILED,
    HOGP_PUSH_FAILED,
    HOGP_OPERATION_FAILED,
} hogp_error_t;

#endif
